services:
  backend:
    build: .
    container_name: mal-stremio-addon
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - SQLITE_PATH=/app/data/app.db
    volumes:
      - sqlite_data:/app/data

  mongo:
    profiles: ["mongo"]
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"   # host:container
    volumes:
      - mongo_data:/data/db

volumes:
  sqlite_data:
  mongo_data:
